// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: matches.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createMatch = `-- name: CreateMatch :one
INSERT INTO matches (id, player1_id, player2_id, created_at)
VALUES (
    gen_random_uuid ( ),
    $1,
    $2,
    NOW()
)
RETURNING id, player1_id, player2_id, winner_id, created_at, completed_at
`

type CreateMatchParams struct {
	Player1ID uuid.UUID
	Player2ID uuid.UUID
}

func (q *Queries) CreateMatch(ctx context.Context, arg CreateMatchParams) (Match, error) {
	row := q.db.QueryRowContext(ctx, createMatch, arg.Player1ID, arg.Player2ID)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.Player1ID,
		&i.Player2ID,
		&i.WinnerID,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getMatchHistory = `-- name: GetMatchHistory :many
SELECT id, player1_id, player2_id, winner_id, created_at, completed_at from matches
WHERE player1_id = $1 OR player2_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetMatchHistory(ctx context.Context, player1ID uuid.UUID) ([]Match, error) {
	rows, err := q.db.QueryContext(ctx, getMatchHistory, player1ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Match
	for rows.Next() {
		var i Match
		if err := rows.Scan(
			&i.ID,
			&i.Player1ID,
			&i.Player2ID,
			&i.WinnerID,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMatchResults = `-- name: UpdateMatchResults :one
UPDATE matches
SET winner_id = $2, completed_at = NOW()
WHERE id = $1 AND winner_id IS NULL AND completed_at IS NULL
RETURNING id, player1_id, player2_id, winner_id, created_at, completed_at
`

type UpdateMatchResultsParams struct {
	ID       uuid.UUID
	WinnerID uuid.NullUUID
}

func (q *Queries) UpdateMatchResults(ctx context.Context, arg UpdateMatchResultsParams) (Match, error) {
	row := q.db.QueryRowContext(ctx, updateMatchResults, arg.ID, arg.WinnerID)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.Player1ID,
		&i.Player2ID,
		&i.WinnerID,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}
