// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Match struct {
	ID          uuid.UUID
	Player1ID   uuid.UUID
	Player2ID   uuid.UUID
	WinnerID    uuid.NullUUID
	CreatedAt   time.Time
	CompletedAt sql.NullTime
}

type User struct {
	ID             uuid.UUID
	Username       string
	Email          string
	HashedPassword string
	CreatedAt      time.Time
	Wins           int32
	Loses          int32
	Rating         int32
}
