-- +goose Up
ALTER TABLE users
ADD COLUMN wins INTEGER NOT NULL DEFAULT 0,
ADD COLUMN loses INTEGER NOT NULL DEFAULT 0,
ADD COLUMN rating INTEGER NOT NULL DEFAULT 1000;

-- +goose Down
ALTER TABLE users
DROP COLUMN wins, 
DROP COLUMN loses, 
DROP COLUMN rating;
